@startuml

start

repeat
  :ゲームリストが表示されているページに飛ぶ;
  :表示されているゲームリストのURLを全て格納;
repeat while (一定以上の情報を入手した？) is (次のページへ)
  :入手した全てのURLをCSVに保存;
  :保存したCSVから全てのURLを取り出し、統計に必要な情報を入手;
  :情報を50個入手する度にCSVに書き込む;

stop

@enduml